# Generated by Django 6.1.1 on 2026-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_marked_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
